apiVersion: v1
kind: Service
metadata:
  name: grafana-sv
  namespace: monitoring
  labels:
    k8s-app: grafana
spec:
  type: NodePort
  ports:
  - name: tcp
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    k8s-app: grafana